name: flutter_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.0.9
  shared_preferences: ^2.0.0
  webview_flutter: ^2.0.13 
  http: ^1.2.1
  intl: ^0.19.0
  win32: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
